apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-ssl
          image: nitrorider/rabbitmq-ssl
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 15672
              name: rbmq-mgmt-http
            - containerPort: 5672
              name: rbmq-msg-tcp
            - containerPort: 15671
              name: rbmq-mgmt-https
            - containerPort: 5671
              name: rbmq-msg-ssl
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
            - name: RABBITMQ_CONFIG_FILES
              value: /etc/rabbitmq/rabbitmq.conf
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rbmq-mgmt-http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rbmq-msg-tcp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rbmq-mgmt-https
      protocol: TCP
      port: 15671
      targetPort: 15671
    - name: rbmq-msg-ssl
      protocol: TCP
      port: 5671
      targetPort: 5671
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: rbmq-mgmt-http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rbmq-msg-tcp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rbmq-mgmt-https
      protocol: TCP
      port: 15671
      targetPort: 15671
    - name: rbmq-msg-ssl
      protocol: TCP
      port: 5671
      targetPort: 5671